
import Home from "@/pages";
import Head from "next/head";
import React from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";


const Layout = ({ title , children }) => {
  return (
    <>
      <Head>
        <title>{title ? title + "-MetaVerses" : "Metaverses"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primary-black overflow-hidden">
        <Navbar/>
        <main style={{ flexGrow : 1 }}>{children}</main>
        <Footer/>
      
      </div>
    </>
  );
};

export default Layout;
