import Head from "next/head";
import React from "react";
import About from "./About";
import Explore from "./Explore";
import GetStarted from "./GetStarted";
import Hero from "./Hero";
import Insights from "./Insights";
import Navbar from "./Navbar";
import WhatsNew from "./WhatsNew";
import World from "./World";

const Layout = ({ title }) => {
  return (
    <>
      <Head>
        <title>{title ? title + "-MetaVerses" : "Metaverses"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primary-black overflow-hidden">
        <Navbar/>
        <Hero/>
        <div className="relative">
        <About/>
        <div className="gradient-03 z-0"/>
        <Explore/>
        </div>
        <div className="relative">
          <GetStarted/>
        <div className="gradient-03 z-0"/>
        <WhatsNew/>
        </div>
        <div className="relative">
          <World/>
        <div className="gradient-03 z-0"/>
        <Insights/>
        </div>
        <div>The websitebody</div>
        <div>Footer</div>
        <div>Footer</div>
        <div>Footer</div>
        <div>Footer</div>
        <div>Footer</div>
        <div>Footer</div>
        <div>Footer</div>
        <div>Footer</div>
        <div>Footer</div>

      </div>
    </>
  );
};

export default Layout;
